"""Capture storage contract; identity, ordering and feedback remain caller policy.

Keys are canonical fixed-width hexadecimal LSN strings; records retain their
existing payload and SHA256 bytes. Prune tokens are backend-private: callers may
return them only to the same owner. No transport, registry or backend selection
is introduced by this contract. Fatal storage errors propagate unchanged.
"""
from typing import Protocol, ContextManager, Iterator


class CommitUncertain(Exception):
    """Owner reopened storage after an ambiguous response; policy must verify it.

    Never acknowledge from this exception. Verify the complete retained chain and
    the proposed group/cursor before accepting, otherwise propagate the cause.
    """
    def __init__(self, cause):
        self.cause=cause
        super().__init__('journal_commit_uncertain')


class ReadBusy(Exception):
    """Retryable read-only contention; the failed snapshot is already closed."""


class Snapshot(Protocol):
    """One pinned view, bounded by the supplied deadline and released before apply.

    Metadata: at most 32 values, 2 MiB each. Record payloads: at most 4 MiB;
    consumer stops at its unchanged 16 MiB materialization budget. Records stream
    in sequence order, with oversized payloads represented by size + None for
    caller validation. Closing finalizes every cursor before releasing the lease.
    """
    def metadata(self) -> dict: ...
    def records(self, after: str, through: str) -> Iterator[tuple]: ...


class Owner(Protocol):
    """One exclusive writer; no metadata value grants backend-specific authority.

    append_group atomically stores at most 128 records / 4 MiB and metadata under
    durable synchronous writes. An ambiguous COMMIT reopens, then raises
    CommitUncertain so the caller revalidates identity and the entire chain.
    establish atomically initializes metadata. prune_group atomically moves the
    caller-verified prefix and deletes only the bounded selected prefix, preserving
    the reconnect anchor. Physical limits and existing checkpoint policy apply.
    """
    limit: int
    def get(self, key: str): ...
    def set(self, key: str, value): ...
    def establish(self, values: dict): ...
    def verify_storage(self): ...
    def records(self) -> Iterator[tuple]: ...
    def replay_anchor(self, end: str): ...
    def record_anchor(self, end: str): ...
    def append_group(self, records: list, metadata: dict): ...
    def prune_candidates(self, through: str) -> list: ...
    def prune_group(self, token, prefix: dict, reclaimed: int, barrier_at): ...
    def backlog_bytes(self, after: str) -> int: ...
    def payloads(self, after: str) -> Iterator[tuple]: ...
    def payload(self, end: str): ...
    def transactions(self, after: str) -> Iterator[tuple]: ...
    def activate(self): ...
    def after_write(self): ...
    def progress(self) -> dict: ...
    def physical(self) -> int: ...
    def close(self): ...


class Reader(Protocol):
    def __call__(self, path, deadline: float, busy_seconds: float) -> ContextManager[Snapshot]: ...
